version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 379735666427.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=379735666427.dkr.ecr.ap-south-1.amazonaws.com/pythonapp:latest
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-50)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t pythonapp .
      - docker tag pythonapp:latest 379735666427.dkr.ecr.ap-south-1.amazonaws.com/pythonapp:latest
  post_build:
    commands:
      - echo Build completed on `date`
<<<<<<< HEAD
      - echo Pushing the Docker images..
      - docker push 379735666427.dkr.ecr.ap-south-1.amazonaws.com/pythonapp:latest
=======
      - echo Pushing the Docker images...
      - docker push 379735666427.dkr.ecr.us-east-1.amazonaws.com/pythonflask:latest
>>>>>>> parent of a2c3d3a (Update buildspec.yaml)
      - echo Writing image definitions file...
      - printf '[{"name":"py-container","imageUri":"%s"}]' 379735666427.dkr.ecr.us-east-1.amazonaws.com/pythonflask:latest > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json
